version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=fptdb
      - MYSQL_ROOT_PASSWORD=12345678

      #Cambiar la imagen a la del dockerhub cuando terminemos de desarrollar
  practica:
    image: jgburjc/fpt
    restart: always
    ports:
      - 8443:8443
    depends_on:
      - db
    environment:
      - WAIT_HOSTS=fptdb:3306
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/fptdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=12345678
