version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=fptdb
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - 3306:3306

  practica:
    image: jgburjc/friendspadeltour:latest
    ports:
      - 8443:8443
    depends_on:
      - db
    environment:
      - WAIT_HOSTS=fptdb:3306
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/fptdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
